/*
 * Settings.java
 *
 */

package com.dnsalias.java.sqlclient;

import javax.swing.*;

/**
 *
 * @author  jbanes
 */
public class Settings extends JInternalFrame 
{
    /** Creates new form Settings */
    public Settings() 
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        panel = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        rightpanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        prefixLabel = new javax.swing.JLabel();
        prefix = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        driverLabel = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();
        bottompanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        save = new javax.swing.JButton();
        newprofile = new javax.swing.JButton();
        
        panel.setLayout(new java.awt.GridLayout(1, 2));
        
        panel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(4, 4, 4, 4)));
        scrollpane.setViewportView(jList1);
        
        panel.add(scrollpane);
        
        rightpanel.setLayout(new java.awt.GridLayout(0, 2, 4, 4));
        
        rightpanel.setBorder(new javax.swing.border.TitledBorder("Profiles"));
        nameLabel.setText("Name:");
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rightpanel.add(nameLabel);
        
        rightpanel.add(name);
        
        prefixLabel.setText("Prefix:");
        prefixLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rightpanel.add(prefixLabel);
        
        rightpanel.add(prefix);
        
        urlLabel.setText("URL:");
        urlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rightpanel.add(urlLabel);
        
        rightpanel.add(url);
        
        driverLabel.setText("Driver:");
        driverLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rightpanel.add(driverLabel);
        
        rightpanel.add(driver);
        
        panel.add(rightpanel);
        
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        
        ok.setText("Ok");
        bottompanel.add(ok);
        
        cancel.setText("Cancel");
        bottompanel.add(cancel);
        
        separator.setForeground(new java.awt.Color(204, 204, 204));
        separator.setPreferredSize(new java.awt.Dimension(10, 10));
        separator.setMinimumSize(new java.awt.Dimension(10, 10));
        bottompanel.add(separator);
        
        save.setText("Save");
        bottompanel.add(save);
        
        newprofile.setText("New");
        newprofile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newprofileActionPerformed(evt);
            }
        });
        
        bottompanel.add(newprofile);
        
        getContentPane().add(bottompanel, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void newprofileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newprofileActionPerformed
    {//GEN-HEADEREND:event_newprofileActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_newprofileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JList jList1;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JTextField prefix;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField url;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JTextField driver;
    private javax.swing.JPanel bottompanel;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton save;
    private javax.swing.JButton newprofile;
    // End of variables declaration//GEN-END:variables

}
