/*
 * SQLFileChooser.java
 *
 */

package com.dnsalias.java.sqlclient;

import java.io.*;
import javax.swing.*;

import com.dnsalias.java.sqlclient.util.*;

/**
 *
 * @author  jbanes
 */
public class SQLFileChooser extends JDialog 
{
    File file = null;
    
    /** Creates new form SQLFileChooser */
    public SQLFileChooser(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        
        if(!MDIFrame.webstart)
        {
            initComponents();

            filechooser.setCurrentDirectory(new File(File.separator));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        filechooser = new javax.swing.JFileChooser();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        filechooser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                filechooserActionPerformed(evt);
            }
        });
        
        getContentPane().add(filechooser, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void filechooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_filechooserActionPerformed
    {//GEN-HEADEREND:event_filechooserActionPerformed
        if(evt.getActionCommand().equalsIgnoreCase("ApproveSelection"))
        {
            file = filechooser.getSelectedFile();
        }
        
        hide();
    }//GEN-LAST:event_filechooserActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public String openDocument() throws IOException
    {
        InputStream in;
        StringBuffer data = new StringBuffer();
        
        if(MDIFrame.webstart)
        {
            in = JNLPServices.open();
            
            if(in == null) return null;
        }
        else
        {
            file = null;
            filechooser.setDialogType(JFileChooser.OPEN_DIALOG);
            filechooser.setDialogTitle("Open");

            show();

            if(file == null) return null;
            in = new FileInputStream(file);
        }
        
        int b = 0;
        
        while((b = in.read()) >= 0)
        {
            data.append((char)b);
        }
        
        in.close();
        
        System.out.println("Loaded: "+data);
        
        return data.toString();
    }
    
    public boolean saveDocument(String data) throws IOException
    {
        FileOutputStream out;
        
        if(MDIFrame.webstart)
        {
            return JNLPServices.save(new ByteArrayInputStream(data.getBytes()));
        }
        else
        {
            file = null;
            filechooser.setDialogType(JFileChooser.SAVE_DIALOG);
            filechooser.setDialogTitle("Save");

            show();

            if(file == null) return false;

            out = new FileOutputStream(file);
            
            out.write(data.getBytes());
            out.close();
            
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser filechooser;
    // End of variables declaration//GEN-END:variables

}
