/*
 * Confirmation.java
 *
 * Created on June 20, 2001, 1:06 AM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  jbanes
 */
public class Confirmation extends JDialog 
{
    private static Confirmation instance = null;
    private static boolean answer = false;
    
    /** Creates new form Confirmation */
    private Confirmation(Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        top = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        labels = new javax.swing.JPanel();
        question = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        top.setLayout(new java.awt.BorderLayout());
        
        top.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        panel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okActionPerformed(evt);
            }
        });
        
        panel.add(ok);
        
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelActionPerformed(evt);
            }
        });
        
        panel.add(cancel);
        
        top.add(panel, java.awt.BorderLayout.CENTER);
        
        labels.setLayout(new java.awt.BorderLayout());
        
        question.setText("Are you sure?");
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labels.add(question, java.awt.BorderLayout.CENTER);
        
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Stop24.gif")));
        icon.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(4, 4, 4, 4)));
        labels.add(icon, java.awt.BorderLayout.WEST);
        
        top.add(labels, java.awt.BorderLayout.NORTH);
        
        getContentPane().add(top, java.awt.BorderLayout.NORTH);
        
        pack();
    }//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelActionPerformed
    {//GEN-HEADEREND:event_cancelActionPerformed
        // Add your handling code here:
        answer = false;
        instance.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        // Add your handling code here:
        answer = true;
        instance.hide();
    }//GEN-LAST:event_okActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        instance.hide();
    }//GEN-LAST:event_closeDialog

    public static synchronized boolean confirm(String question, Component parent)
    {
        int selected = JOptionPane.showInternalConfirmDialog(parent, question);
        
        return (selected == 0);
        
        /*if(instance == null) instance = new Confirmation(parent, true);
        
        answer = false;
        instance.question.setText(question);
        
        instance.pack();
        instance.setLocation(parent.getX()+parent.getWidth()/2-instance.getWidth()/2, parent.getY()+parent.getHeight()/2-instance.getHeight()/2);
        instance.show();
        
        return answer;*/
    }
    
    public static void main(String[] args)
    {
        System.out.println(Confirmation.confirm("Are you sure?", new Frame()));
        System.exit(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel top;
    private javax.swing.JPanel panel;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel labels;
    private javax.swing.JLabel question;
    private javax.swing.JLabel icon;
    // End of variables declaration//GEN-END:variables

}
