/*
 * DownloadMonitor.java
 *
 * Created on May 11, 2002, 7:50 PM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;

import com.dnsalias.java.sqlclient.util.*;

/**
 *
 * @author  jbanes
 */
public class DownloadMonitor extends javax.swing.JDialog
{
    private boolean cancelled = false;
    
    /** Creates new form DownloadMonitor */
    private DownloadMonitor(java.awt.Frame parent)
    {
        super(parent, false);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        download = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();
        totals = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        
        setTitle("Downloading Driver...");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        download.setLayout(new java.awt.GridLayout(0, 1, 0, 4));
        
        download.setBorder(new javax.swing.border.TitledBorder("Downloading driver"));
        progress.setPreferredSize(new java.awt.Dimension(300, 14));
        download.add(progress);
        
        totals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        download.add(totals);
        
        getContentPane().add(download, java.awt.BorderLayout.CENTER);
        
        buttons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        
        buttons.add(jButton1);
        
        getContentPane().add(buttons, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        cancelled = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(true);
    }//GEN-LAST:event_closeDialog

    public static boolean download(Frame parent, Downloader loader)
    {
        if(loader == null) return true;

        DownloadMonitor monitor = new DownloadMonitor(parent);
        
        monitor.setLocation(
            parent.getX() + (parent.getWidth()/2) - (monitor.getWidth()/2), 
            parent.getY() +  (parent.getHeight()/2) - (monitor.getHeight()/2));
        monitor.setVisible(true);
        
        while(!loader.completed() && !loader.stopped())
        {
            monitor.progress.setValue(loader.getProgressInPercent());
            monitor.totals.setText("Downloaded "+loader.getProgress()+" of "+loader.getLength()+" bytes");
            
            try{Thread.sleep(100);} catch(InterruptedException e) {}
            
            if(monitor.cancelled) loader.cancel();
        }

        monitor.setVisible(false);
        monitor.dispose();
        
        return loader.completed();
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        new DownloadMonitor(new javax.swing.JFrame()).show();
    }

    public void run()
    {
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel download;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel totals;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
