/*
 * ErrorReport.java
 *
 * Created on June 24, 2001, 1:16 PM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;
import java.io.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author  jbanes
 */
public class ErrorReport extends JDialog 
{
    private static ErrorReport instance = null;
    
    private JScrollPane dynamic = new JScrollPane();
    private JTextArea textarea = new JTextArea();
    private boolean detail = false;
    
    /** Creates new form ErrorReport */
    private ErrorReport(Frame parent, boolean modal) 
    {
        super(parent, modal);
        
        initComponents();
        
        dynamic.setViewportView(textarea);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        details = new javax.swing.JButton();
        dynamicPanel = new javax.swing.JPanel();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        mainPanel.setLayout(new java.awt.BorderLayout());
        
        mainPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incors/plaf/kunststoff/icons/Error.gif")));
        icon.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(4, 4, 4, 10)));
        jPanel3.add(icon);
        
        mainPanel.add(jPanel3, java.awt.BorderLayout.WEST);
        
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));
        
        message.setText("Are you sure?");
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(message);
        
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jPanel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okActionPerformed(evt);
            }
        });
        
        jPanel2.add(ok);
        
        details.setText("Details >>");
        details.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                detailsActionPerformed(evt);
            }
        });
        
        jPanel2.add(details);
        
        jPanel4.add(jPanel2);
        
        mainPanel.add(jPanel4, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        
        dynamicPanel.setLayout(new java.awt.BorderLayout());
        
        getContentPane().add(dynamicPanel, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        // Add your handling code here:
        hide();
    }//GEN-LAST:event_okActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_detailsActionPerformed
    {//GEN-HEADEREND:event_detailsActionPerformed
        // Add your handling code here:
        
        if(!detail)
        {
            dynamicPanel.add(dynamic);
            details.setText("Details <<");
        }
        else 
        {
            dynamicPanel.remove(dynamic);
            details.setText("Details >>");
        }
        
        getRootPane().revalidate();
        
        pack();
        
        detail = !detail;
    }//GEN-LAST:event_detailsActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog

    public static synchronized void displayError(Exception e, Component parent)
    {
        displayError(e.getMessage(), e, parent);
    }

    public static synchronized void displayError(String message, Exception e, Component parent)
    {
        while(parent.getParent() != null) parent = parent.getParent();
        
        if(instance == null) instance = new ErrorReport((Frame)parent, true);
        
        StringWriter trace = new StringWriter();
        Dimension dim = instance.getToolkit().getScreenSize();
        
        e.printStackTrace(new PrintWriter(trace));
        instance.message.setText("<html><body><p>"+message+"</p></body></html>");
        instance.textarea.setText(trace.toString());
        
        instance.pack();
        instance.setLocation(dim.width/2-instance.getWidth()/2, dim.height/2-instance.getHeight()/2);
        instance.show();
    }

    public void pack()
    {
        dynamic.setPreferredSize(new Dimension(0, 200));
        super.pack();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel message;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok;
    private javax.swing.JButton details;
    private javax.swing.JPanel dynamicPanel;
    // End of variables declaration//GEN-END:variables

}
