/*
 * LicenseAgreement.java
 *
 * Created on May 11, 2002, 3:42 PM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.io.*;

/**
 *
 * @author  jbanes
 */
public class LicenseAgreement extends javax.swing.JFrame 
{
    public static final String ACCEPTED = "Accepted";
    public static final String DECLINED = "Declined";
    
    private String chosen = null;
    
    public LicenseAgreement() throws IOException
    {
        initComponents();
        
        display.setPage(getClass().getResource("/license.html"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        buttons = new javax.swing.JPanel();
        accept = new javax.swing.JButton();
        decline = new javax.swing.JButton();
        licensePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        display = new javax.swing.JEditorPane();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });
        
        buttons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        accept.setText("Accept");
        accept.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acceptActionPerformed(evt);
            }
        });
        
        buttons.add(accept);
        
        decline.setText("Decline");
        decline.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                declineActionPerformed(evt);
            }
        });
        
        buttons.add(decline);
        
        getContentPane().add(buttons, java.awt.BorderLayout.SOUTH);
        
        licensePanel.setLayout(new java.awt.BorderLayout());
        
        licensePanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 180), 2, true), "License Agreement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18)));
        display.setBorder(null);
        display.setEditable(false);
        display.setContentType("text/html");
        scrollPane.setViewportView(display);
        
        licensePanel.add(scrollPane, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(licensePanel, java.awt.BorderLayout.CENTER);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(640, 480));
        setLocation((screenSize.width-640)/2,(screenSize.height-480)/2);
    }//GEN-END:initComponents

    private void declineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_declineActionPerformed
    {//GEN-HEADEREND:event_declineActionPerformed
        chosen = DECLINED;
        setVisible(false);
    }//GEN-LAST:event_declineActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acceptActionPerformed
    {//GEN-HEADEREND:event_acceptActionPerformed
        chosen = ACCEPTED;
        setVisible(false);
    }//GEN-LAST:event_acceptActionPerformed

    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //do nothing
    }//GEN-LAST:event_exitForm

    public static boolean showLicense()
    {
        try
        {
            LicenseAgreement agreement = new LicenseAgreement();
            boolean accepted = false;
            
            agreement.setVisible(true);
            
            while(agreement.chosen == null)
            {
                try{Thread.sleep(500);}catch(InterruptedException e) {}
            }
            
            accepted = (agreement.chosen == ACCEPTED);
            agreement.dispose();
            
            return accepted;
        }
        catch(Exception e)
        {
            e.printStackTrace();
            return false;
        }
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        try
        {
            new LicenseAgreement().show();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private javax.swing.JButton accept;
    private javax.swing.JButton decline;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JEditorPane display;
    // End of variables declaration//GEN-END:variables

}
