/*
 * LicenseManager.java
 *
 * Created on June 6, 2002, 11:31 AM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;
import java.util.*;

import javax.swing.*;

import com.dnsalias.java.sqlclient.util.*;
import com.dnsalias.java.sqlclient.validation.*;

/**
 *
 * @author  jbanes
 */
public class LicenseManager extends javax.swing.JInternalFrame 
{
    private JTextField one = new LicenseKeyEditor();
    private JTextField two = new LicenseKeyEditor();
    private JTextField three = new LicenseKeyEditor();
    
    /** Creates new form LicenseManager */
    public LicenseManager() 
    {
        initComponents();
        
        one.setNextFocusableComponent(two);
        two.setNextFocusableComponent(three);
        
        one.setFont(new Font("Courier New", Font.PLAIN, one.getFont().getSize()));
        two.setFont(new Font("Courier New", Font.PLAIN, one.getFont().getSize()));
        three.setFont(new Font("Courier New", Font.PLAIN, one.getFont().getSize()));
        
        one.setColumns(6);
        two.setColumns(6);
        three.setColumns(6);
        
        mainPanel.add(one);
        mainPanel.add(new JLabel("-"));
        mainPanel.add(two);
        mainPanel.add(new JLabel("-"));
        mainPanel.add(three);
        
        if(ApplicationSettings.getInstance().getProperty("license-key") != null)
        {
            String key = ApplicationSettings.getInstance().getProperty("license-key");
            
            one.setText(key.substring(0, 4));
            two.setText(key.substring(4, 8));
            three.setText(key.substring(8, 12));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        mainPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        instuctions = new javax.swing.JLabel();
        
        setTitle("License Key Manager");
        setClosable(true);
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });
        
        buttonPanel.add(okButton);
        
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });
        
        buttonPanel.add(cancelButton);
        
        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        jPanel3.setLayout(new java.awt.BorderLayout());
        
        instuctions.setText("Enter your license key below:");
        instuctions.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        jPanel3.add(instuctions, java.awt.BorderLayout.NORTH);
        
        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);
        
        setBounds(15, 15, 250, 130);
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        try
        {
            String key = one.getText()+two.getText()+three.getText();
            
            KeyInfo info = new KeyInfo(key);
            
            if(info.trial && info.date.before(new Date()))
            {
                JOptionPane.showMessageDialog(getParent(), "This is an expired trial key!");
                return;
            }
            
            ApplicationSettings.getInstance().setPesistentProperty("license-key", key);
            
            if(info.trial) JOptionPane.showMessageDialog(getParent(), "You are ready to evaluate our advanced features!", "", JOptionPane.INFORMATION_MESSAGE);    
            else JOptionPane.showMessageDialog(getParent(), "Thank you for purchasing our product!", "", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
            JOptionPane.showMessageDialog(getParent(), "We're sorry, but this key is invalid.", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel instuctions;
    // End of variables declaration//GEN-END:variables

}
