/*
 * ReviewText.java
 *
 * Created on May 29, 2002, 7:35 PM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;

import javax.swing.*;

/**
 *
 * @author  jbanes
 */
public class ReviewText extends JDialog 
{   
    private boolean accepted = false;
    
    public ReviewText(Frame parent, String text) 
    {
        super(parent, true);
        initComponents();
        
        this.text.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        mainPanel = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        mainPanel.setLayout(new java.awt.BorderLayout());
        
        mainPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        text.setWrapStyleWord(true);
        text.setFont(new java.awt.Font("Courier", 0, 12));
        text.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        scroll.setViewportView(text);
        
        mainPanel.add(scroll, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okActionPerformed(evt);
            }
        });
        
        buttonPanel.add(ok);
        
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelActionPerformed(evt);
            }
        });
        
        buttonPanel.add(cancel);
        
        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        jLabel1.setText("Please review the SQL and make any desired changes:");
        jLabel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(400, 350));
        setLocation((screenSize.width-400)/2,(screenSize.height-350)/2);
    }//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelActionPerformed
    {//GEN-HEADEREND:event_cancelActionPerformed
        dispose();
        
        accepted = false;
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        dispose();
        
        accepted = true;
    }//GEN-LAST:event_okActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
        
        accepted = false;
    }//GEN-LAST:event_closeDialog

    public String getText()
    {
        return text.getText();
    }
    
    public boolean accepted()
    {
        return accepted;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea text;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
