/*
 * SelectDriver.java
 *
 * Created on May 15, 2002, 6:54 PM
 */

package com.dnsalias.java.sqlclient.dialog;

import java.awt.*;

/**
 *
 * @author  jbanes
 */
public class SelectDriver extends javax.swing.JDialog {

    /** Creates new form SelectDriver */
    public SelectDriver(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        information = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        driverLocation = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        information.setText("<html><body>This database requires that you already have drivers installed on your<br>\nsystem. Please enter the name of the driver file:</body></html>");
        getContentPane().add(information, java.awt.BorderLayout.NORTH);
        
        mainPanel.setLayout(null);
        
        mainPanel.add(driverLocation);
        driverLocation.setBounds(10, 10, 280, 21);
        
        browse.setText("Browse...");
        browse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseActionPerformed(evt);
            }
        });
        
        mainPanel.add(browse);
        browse.setBounds(300, 10, 87, 27);
        
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okActionPerformed(evt);
            }
        });
        
        buttonPanel.add(ok);
        
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelActionPerformed(evt);
            }
        });
        
        buttonPanel.add(cancel);
        
        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseActionPerformed
    {//GEN-HEADEREND:event_browseActionPerformed
        Component parent = this;
        FileDialog chooser;
        
        while(parent.getParent() != null) parent = parent.getParent();
        
        chooser = new FileDialog((Frame)parent, "Find Driver...", FileDialog.LOAD);
        chooser.setVisible(true);
        driverLocation.setText(chooser.getFile());
    }//GEN-LAST:event_browseActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelActionPerformed
    {//GEN-HEADEREND:event_cancelActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        new SelectDriver(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel information;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField driverLocation;
    private javax.swing.JButton browse;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    // End of variables declaration//GEN-END:variables

}
