/*
 * FileSystemTree.java
 *
 * Created on December 17, 2002, 7:55 PM
 */

package com.datadino.sqlclient.ui;

import java.awt.*;
import java.io.*;
import java.util.*;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.filechooser.*;
import javax.swing.tree.*;

/**
 *
 * @author  jbanes
 */
public class FileSystemTree extends JDialog 
{
    private FileSystemTreeModel model;
    
    private File result = null;
    private boolean canceled = true;
    
    /** Creates new form FileSystemTree */
    public FileSystemTree(Frame parent, boolean modal) 
    {
        this(parent, modal, false);
    }
    
    public FileSystemTree(Frame parent, boolean modal, boolean directoriesOnly) 
    {
        super(parent, modal);
        initComponents();
        
        setTitle(directoriesOnly ? "Select Directory..." : "Select File...");
        model = new FileSystemTreeModel(directoriesOnly);
        
        tree.setModel(model);
        tree.setCellRenderer(new FileSystemTreeCellRenderer());
        tree.getSelectionModel().addTreeSelectionListener(new FSTreeSelectionListener());
        
        setSize(350, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        scroll = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        scroll.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)), new javax.swing.border.EtchedBorder()));
        scroll.setViewportView(tree);
        
        getContentPane().add(scroll, java.awt.BorderLayout.CENTER);
        
        okButton.setText("Ok");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });
        
        jPanel1.add(okButton);
        
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });
        
        jPanel1.add(cancelButton);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        canceled = true;
        result = null;
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        canceled = false;
        result = (File)tree.getSelectionPath().getLastPathComponent();
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    public boolean isCanceled()
    {
        return canceled;
    }
    
    public File getSelectedFile()
    {
        return result;
    }
    
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        cancelButtonActionPerformed(null);
    }//GEN-LAST:event_closeDialog

    private class FileSystemTreeCellRenderer extends JLabel implements TreeCellRenderer
    {
        private DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        private DefaultTreeCellRenderer defaultRenderer = new DefaultTreeCellRenderer();
        private FileSystemView fs = FileSystemView.getFileSystemView();
        
        private boolean enhanced = false;
        
        public FileSystemTreeCellRenderer()
        {
            if(System.getProperty("java.vm.version").startsWith("1.3")) enhanced = false;
            else enhanced = true;
        }
        
        public Component getTreeCellRendererComponent(JTree tree, Object obj, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus)
        {
            String name;
            Icon icon;
            
            if(!(obj instanceof File)) return defaultRenderer;
            
            name = ((File)obj).getName();
            
            if(enhanced)
            {
                icon = fs.getSystemIcon((File)obj);
                
                renderer.setClosedIcon(icon);
                renderer.setOpenIcon(icon);
                renderer.setLeafIcon(icon);
                
                name = fs.getSystemDisplayName((File)obj);
            }
            
            if(name.trim().length() < 1) name = obj.toString();
            
            return renderer.getTreeCellRendererComponent(tree, name, selected, expanded, leaf, row, hasFocus);
        }
    }
    
    private class FSTreeSelectionListener implements TreeSelectionListener
    {
        public void valueChanged(TreeSelectionEvent evt)
        {
            if(evt.getPath() != null) okButton.setEnabled(true);
            else okButton.setEnabled(false);
        }
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        new FileSystemTree(new javax.swing.JFrame(), true, false).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTree tree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
